// Generated by CoffeeScript 1.7.1
(function() {
  var app, config, connect, db, express, fs, http, passAuth, response, sqlite3;

  http = require('http');

  fs = require('fs');

  connect = require('connect');

  sqlite3 = require('sqlite3').verbose();

  express = require('express');

  config = JSON.parse(fs.readFileSync('config.json'));

  db = new sqlite3.Database('db.sqlite');

  response = function(res, msg) {
    return res.send(JSON.stringify(msg));
  };

  passAuth = function(query) {
    var hmac, key, signature, username;
    username = query.username, signature = query.signature;
    if (signature == null) {
      return false;
    }
    if (config.users[username] == null) {
      return false;
    }
    delete query.signature;
    key = (new Buffer(config.users[username].passphrase)).toString('hex');
    hmac = crypto.createHmac('sha512', key);
    hmac.setEncoding('hex');
    hmac.write(JSON.stringify(query));
    hmac.end();
    return hmac.read() === signature;
  };

  app = express();

  app.use(function(req, res, next) {
    var passphrase, signature, username, _ref;
    if (!passAuth(req.query)) {
      response({
        error: "Fail to auth"
      });
      return;
    }
    _ref = req.query, username = _ref.username, signature = _ref.signature;
    passphrase = "passphrase";
    delete req.query.signature;
    return HmacSHA512(JSON.stringify(req.query), passphrase);
  });

  app.listen(config.blog.port);

}).call(this);
